route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifier'
  routes:
    - match:
        receiver: 'telegram-notifier'
      continue: true
receivers:
  - name: default-telegram
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: 6714849193:AAH8eeCCrd1vmEmijVJ55Df7FArmooEvxHc
        chat_id: 1626517174
        disable_notifications: false
        http_config:
          follow_redirects: true
        send_resolved: true
        parse_mode: ""

  - name: 'email-notifier'
    email_configs:
      - to: 'ddta.1389@gmail.com'
        from: 'tienanhbghd@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'tienanhbghd@gmail.com'
        auth_identity: 'tienanhbghd@gmail.com'
        auth_password: 'swrj pjuk feil miaf'
        send_resolved: true
        require_tls: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

templates:
- /etc/alertmanager/config/*.tmpl
