{
 "title": "Monitor Services",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Prometheus Uptime",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"localhost:9090\",job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})"
    }
   ]
  },
  {
   "title": "In-Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks" }
   ]
  },
  {
   "title": "In-Memory Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series" }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{container_label_org_label_schema_group=\"monitoring\"}[1m]) * 100  / scalar(count(node_cpu_seconds_total{mode=\"user\"})))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{container_label_org_label_schema_group=\"monitoring\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Prometheus Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"prometheus\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
     "legendFormat": "Target heap size"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"prometheus\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"prometheus\"}[1m])",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Head Time series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "Time series" }
   ]
  },
  {
   "title": "Head Active Appenders",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_active_appenders",
     "legendFormat": "Head Appenders"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[1m])",
     "legendFormat": "Samples"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "Chunks" }
   ]
  },
  {
   "title": "Head Chunks Created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_chunks_created_total[1m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Head Time Range",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    { "expr": "prometheus_tsdb_head_min_time", "legendFormat": "Min" },
    { "expr": "time() * 1000", "legendFormat": "Now" },
    { "expr": "prometheus_tsdb_head_max_time", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Target Scrapes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{ interval }}"
    }
   ]
  },
  {
   "title": "Time spent in HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "TSDB Reloads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total[10m])",
     "legendFormat": "Reloads"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_sum[1m]) / rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Evaluation time of rule groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_duration_seconds_sum[1m])",
     "legendFormat": "Rule evaluation duration"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Query engine timings",
   "type": "graph",
   "description": "Time spent in each mode, per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_sum[1m])",
     "legendFormat": "{{slice}}"
    }
   ]
  }
 ]
}