global:
  scrape_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - '194.233.74.59:9093'

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['194.233.74.59:9100']
- job_name: 'cadvisor'
  scrape_interval: 5s
  static_configs:
  - targets: ['194.233.74.59:8081']
- job_name: 'mongodb'
  scrape_interval: 5s
  static_configs:
  - targets: ['194.233.74.59:9216']
- job_name: 'prometheus'
  scrape_interval: 10s
  static_configs:
  - targets: ['194.233.74.59:9090']
- job_name: 'VPS2-node'
  scrape_interval: 10s
  static_configs:
  - targets: ['103.179.173.49:9100']
- job_name: 'VPS2-prometheus'
  scrape_interval: 10s
  static_configs:
  - targets: ['103.179.173.49:9090']
